#!/bin/bash

# 获取所有分支
branches=$(git for-each-ref --format='%(refname:short)' refs/heads/ refs/remotes/origin/)

# 遍历每个分支
for branch in $branches; do
    branch_name=$(basename "$branch")
    echo "Checking out branch: $branch_name"
    mkdir -p "../$branch_name"
    git worktree add "../$branch_name" "$branch"
done
